export type UsageSource = "provider_reported" | "estimated" | "unavailable";
export type UsageRole = "planner" | "executor" | "reviewer" | "repair";
export type CostSource = "provider_reported" | "configured_price" | "unavailable";

export interface UsageValues { readonly inputTokens: number | null; readonly outputTokens: number | null; readonly totalTokens: number | null; readonly usageSource: UsageSource; }
export interface RoleUsage extends UsageValues { readonly role: UsageRole; readonly providerConfigId: string | null; readonly providerId: string | null; readonly requestedModelId: string | null; readonly resolvedModelId: string | null; readonly executionProfileSummary: ExecutionProfileSummary | null; readonly calls: number; readonly providerDurationMs: number | null; readonly contextFiles: number | null; readonly contextBytes: number | null; readonly contextTruncated: boolean | null; readonly targetedExpansions: number; readonly providerReportedCost: number | null; readonly estimatedCost: number | null; readonly currency: string | null; readonly costSource: CostSource; }
export interface TaskUsage extends UsageValues { readonly taskId: string; readonly executorCalls: number; readonly providerDurationMs: number | null; readonly toolCalls: number; readonly toolDurationMs?: number | null; readonly successfulToolCalls?: number; readonly failedToolCalls?: number; readonly invalidToolCalls?: number; readonly toolCallsByName?: Readonly<Record<string, number>>; readonly contextFiles?: number | null; readonly contextBytes: number | null; readonly contextTruncated?: boolean | null; readonly targetedExpansions?: number; }
export interface ValidationUsage { readonly status: "passed" | "failed" | "unavailable"; readonly durationMs: number | null; readonly steps: readonly { readonly name: string; readonly status: string; readonly durationMs: number | null }[]; }
export interface WorkflowUsage {
  readonly workflowId: string; readonly planner: RoleUsage; readonly executor: RoleUsage; readonly reviewer: RoleUsage; readonly repair: RoleUsage; readonly tasks: readonly TaskUsage[];
  readonly totalProviderCalls: number; readonly totalInputTokens: number | null; readonly totalOutputTokens: number | null; readonly totalTokens: number | null; readonly totalProviderDurationMs: number | null; readonly totalToolCalls: number;
  readonly usageSource: UsageSource; readonly providerReportedCost: number | null; readonly estimatedCost: number | null; readonly currency: string | null; readonly costSource: CostSource;
  readonly totalDurationMs?: number | null;
  readonly modelRequestedToolCalls?: number; readonly executedToolCalls?: number; readonly successfulToolCalls?: number; readonly failedToolCalls?: number; readonly invalidToolCalls?: number; readonly toolCallsByName?: Readonly<Record<string, number>>; readonly toolDurationMs?: number | null;
  readonly repairCycles: number; readonly repairSummary?: { readonly cycles: number; readonly calls: number; readonly providerDurationMs: number | null; readonly totalDurationMs: number | null; readonly tokens: number | null };
  readonly validation?: ValidationUsage; readonly review?: { readonly status: string; readonly calls: number; readonly providerDurationMs: number | null; readonly totalDurationMs: number | null };
  readonly contextFiles?: number | null; readonly contextBytes?: number | null; readonly contextTruncated?: boolean; readonly targetedExpansions?: number; readonly localOrchestrationDurationMs?: number | null;
  readonly tokensPerProviderCall?: number | null; readonly inputTokensPerContextKb?: number | null; readonly tokensPerTask?: number | null;
  readonly byProviderModel?: readonly { readonly role: UsageRole; readonly providerId: string; readonly requestedModelId: string | null; readonly resolvedModelId: string | null; readonly calls: number; readonly totalTokens: number | null }[];
}
export interface UsageRecord { readonly role: UsageRole; readonly providerConfigId?: string; readonly providerId?: string; readonly requestedModelId?: string; readonly resolvedModelId?: string; readonly executionProfileSummary?: ExecutionProfileSummary; readonly taskId?: string; readonly inputTokens?: number | null; readonly outputTokens?: number | null; readonly totalTokens?: number | null; readonly usageSource?: UsageSource; readonly providerDurationMs?: number | null; readonly toolCalls?: number; readonly contextFiles?: number | null; readonly contextBytes?: number | null; readonly contextTruncated?: boolean | null; readonly targetedExpansions?: number; readonly providerReportedCost?: number | null; readonly currency?: string | null; }

const finite = (value: unknown): number | null => typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : null;
export function normalizeUsage(value: unknown): UsageValues {
  const v = value && typeof value === "object" ? value as Record<string, unknown> : undefined;
  const inputTokens = finite(v?.inputTokens ?? v?.prompt_tokens ?? v?.promptTokens);
  const outputTokens = finite(v?.outputTokens ?? v?.completion_tokens ?? v?.completionTokens);
  const totalTokens = finite(v?.totalTokens ?? v?.total_tokens) ?? (inputTokens !== null && outputTokens !== null ? inputTokens + outputTokens : null);
  return { inputTokens, outputTokens, totalTokens, usageSource: v?.usageSource === "estimated" ? "estimated" : (inputTokens !== null || outputTokens !== null || totalTokens !== null ? "provider_reported" : "unavailable") };
}
const emptyRole = (role: UsageRole): RoleUsage => ({ role, providerConfigId: null, providerId: null, requestedModelId: null, resolvedModelId: null, executionProfileSummary: null, calls: 0, inputTokens: null, outputTokens: null, totalTokens: null, usageSource: "unavailable", providerDurationMs: null, contextFiles: null, contextBytes: null, contextTruncated: null, targetedExpansions: 0, providerReportedCost: null, estimatedCost: null, currency: null, costSource: "unavailable" });
const sum = (values: readonly (number | null)[]): number | null => values.length > 0 && values.every(v => v !== null) ? values.reduce((a, v) => a + (v as number), 0) : null;

export function aggregateWorkflowUsage(workflowId: string, records: readonly UsageRecord[], meta: { contextFiles?: number | null; contextBytes?: number | null; contextTruncated?: boolean; targetedExpansions?: number; totalDurationMs?: number; toolDurationMs?: number; validationDurationMs?: number; repairCycles?: number; repairDurationMs?: number | null; validation?: ValidationUsage; review?: { status: string; calls: number; providerDurationMs: number | null; totalDurationMs: number | null } } = {}): WorkflowUsage {
  const byRole = new Map<UsageRole, UsageRecord[]>(); for (const record of records) byRole.set(record.role, [...(byRole.get(record.role) ?? []), record]);
  const role = (name: UsageRole): RoleUsage => { const rows = byRole.get(name) ?? []; if (rows.length === 0) return emptyRole(name); const values = rows.map(normalizeUsage); const cost = sum(rows.map(r => finite(r.providerReportedCost))); const common = (select: (row: UsageRecord) => string | undefined): string | null => { const found = [...new Set(rows.map(select).filter((v): v is string => v !== undefined))]; return found.length === 1 ? found[0]! : null; }; const profiles = [...new Map(rows.filter(r => r.executionProfileSummary).map(r => [JSON.stringify(r.executionProfileSummary), r.executionProfileSummary!])).values()]; const truncations = rows.map(r => r.contextTruncated).filter((v): v is boolean => typeof v === "boolean"); return { ...emptyRole(name), providerConfigId: common(r => r.providerConfigId), providerId: common(r => r.providerId), requestedModelId: common(r => r.requestedModelId), resolvedModelId: common(r => r.resolvedModelId), executionProfileSummary: profiles.length === 1 ? profiles[0]! : null, calls: rows.length, inputTokens: sum(values.map(v => v.inputTokens)), outputTokens: sum(values.map(v => v.outputTokens)), totalTokens: sum(values.map(v => v.totalTokens)), usageSource: values.every(v => v.usageSource === "provider_reported") ? "provider_reported" : values.some(v => v.usageSource === "estimated") ? "estimated" : "unavailable", providerDurationMs: sum(rows.map(r => finite(r.providerDurationMs))), contextFiles: sum(rows.map(r => finite(r.contextFiles))), contextBytes: sum(rows.map(r => finite(r.contextBytes))), contextTruncated: truncations.length === rows.length ? truncations.some(Boolean) : null, targetedExpansions: rows.reduce((n, r) => n + (r.targetedExpansions ?? 0), 0), providerReportedCost: cost, currency: common(r => r.currency ?? undefined), costSource: cost !== null ? "provider_reported" : "unavailable" }; };
  const roles = (["planner", "executor", "reviewer", "repair"] as const).map(role);
  const total = (key: "inputTokens" | "outputTokens" | "totalTokens"): number | null => { const active = roles.filter(r => r.calls > 0); return active.length ? sum(active.map(r => r[key])) : null; };
  const totalProviderDurationMs = (() => { const active = roles.filter(r => r.calls > 0); return active.length ? sum(active.map(r => r.providerDurationMs)) : null; })();
  const tasks: TaskUsage[] = [...new Set(records.filter(r => r.role === "executor" && r.taskId).map(r => r.taskId!))].map(taskId => { const rows = records.filter(r => r.role === "executor" && r.taskId === taskId); const values = rows.map(normalizeUsage); const truncations = rows.map(r => r.contextTruncated).filter((v): v is boolean => typeof v === "boolean"); return { taskId, executorCalls: rows.length, inputTokens: sum(values.map(v => v.inputTokens)), outputTokens: sum(values.map(v => v.outputTokens)), totalTokens: sum(values.map(v => v.totalTokens)), usageSource: values.every(v => v.usageSource === "provider_reported") ? "provider_reported" : values.some(v => v.usageSource === "estimated") ? "estimated" : "unavailable", providerDurationMs: sum(rows.map(r => finite(r.providerDurationMs))), toolCalls: rows.reduce((n, r) => n + (r.toolCalls ?? 0), 0), contextFiles: sum(rows.map(r => finite(r.contextFiles))), contextBytes: sum(rows.map(r => finite(r.contextBytes))), contextTruncated: truncations.length === rows.length ? truncations.some(Boolean) : null, targetedExpansions: rows.reduce((n, r) => n + (r.targetedExpansions ?? 0), 0) }; });
  const groups = new Map<string, UsageRecord[]>(); for (const record of records) { const key = `${record.role}|${record.providerId ?? "unknown"}|${record.requestedModelId ?? ""}|${record.resolvedModelId ?? ""}`; groups.set(key, [...(groups.get(key) ?? []), record]); }
  const byProviderModel = [...groups.values()].map(rows => ({ role: rows[0]!.role, providerId: rows[0]!.providerId ?? "unknown", requestedModelId: rows[0]!.requestedModelId ?? null, resolvedModelId: rows[0]!.resolvedModelId ?? null, calls: rows.length, totalTokens: sum(rows.map(r => normalizeUsage(r).totalTokens)) }));
  const totalTokens = total("totalTokens"); const local = meta.totalDurationMs !== undefined && totalProviderDurationMs !== null && meta.toolDurationMs !== undefined && meta.validationDurationMs !== undefined ? Math.max(0, meta.totalDurationMs - totalProviderDurationMs - meta.toolDurationMs - meta.validationDurationMs) : null; const repair = roles[3]!;
  const activeRoles = roles.filter(role => role.calls > 0); const usageSource: UsageSource = activeRoles.length > 0 && activeRoles.every(role => role.usageSource === "provider_reported") ? "provider_reported" : activeRoles.length > 0 && activeRoles.every(role => role.usageSource !== "unavailable") && activeRoles.some(role => role.usageSource === "estimated") ? "estimated" : "unavailable";
  const providerReportedCost = activeRoles.length ? sum(activeRoles.map(role => role.providerReportedCost)) : null; const currencies = [...new Set(activeRoles.map(role => role.currency).filter((value): value is string => value !== null))];
  return { workflowId, planner: roles[0]!, executor: roles[1]!, reviewer: roles[2]!, repair, tasks, totalProviderCalls: records.length, totalInputTokens: total("inputTokens"), totalOutputTokens: total("outputTokens"), totalTokens, totalProviderDurationMs, usageSource, providerReportedCost, estimatedCost: null, currency: currencies.length === 1 ? currencies[0]! : null, costSource: providerReportedCost !== null ? "provider_reported" : "unavailable", totalDurationMs: meta.totalDurationMs ?? null, totalToolCalls: tasks.reduce((n, t) => n + t.toolCalls, 0), ...(meta.toolDurationMs !== undefined ? { toolDurationMs: meta.toolDurationMs } : {}), repairCycles: meta.repairCycles ?? 0, repairSummary: { cycles: meta.repairCycles ?? 0, calls: repair.calls, providerDurationMs: repair.providerDurationMs, totalDurationMs: meta.repairDurationMs ?? null, tokens: repair.totalTokens }, ...(meta.validation ? { validation: meta.validation } : {}), ...(meta.review ? { review: meta.review } : {}), ...(meta.contextFiles !== undefined ? { contextFiles: meta.contextFiles } : {}), ...(meta.contextBytes !== undefined ? { contextBytes: meta.contextBytes } : {}), ...(meta.contextTruncated !== undefined ? { contextTruncated: meta.contextTruncated } : {}), ...(meta.targetedExpansions !== undefined ? { targetedExpansions: meta.targetedExpansions } : {}), localOrchestrationDurationMs: local, tokensPerProviderCall: totalTokens !== null && records.length ? totalTokens / records.length : null, inputTokensPerContextKb: total("inputTokens") !== null && (meta.contextBytes ?? 0) > 0 ? (total("inputTokens") as number) / ((meta.contextBytes as number) / 1024) : null, tokensPerTask: totalTokens !== null && tasks.length ? totalTokens / tasks.length : null, byProviderModel };
}
export type ExecutionProfileSummary =
  | { readonly kind: "provider_default" }
  | { readonly kind: "openai_reasoning"; readonly value: string }
  | { readonly kind: "anthropic_thinking"; readonly enabled: true; readonly budgetTokens: number }
  | { readonly kind: "gemini_thinking_budget"; readonly budgetTokens: number }
  | { readonly kind: "gemini_thinking_level"; readonly value: string };
